set_property PACKAGE_PIN L16 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk]

set_property PACKAGE_PIN Y16 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN R19 [get_ports vSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports vSYNC]

set_property PACKAGE_PIN P19 [get_ports hSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports hSYNC]

set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports {R[0]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {R[1]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {R[2]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {R[3]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {R[4]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {G[0]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports {G[1]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {G[2]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {G[3]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports {G[4]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {G[5]}]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports {B[0]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {B[1]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports {B[2]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {B[3]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {B[4]}]

set_property PACKAGE_PIN T16 [get_ports {rot_sw[1]}]
set_property PACKAGE_PIN W13 [get_ports {rot_sw[0]}]
set_property PACKAGE_PIN P15 [get_ports {scala_sw[1]}]
set_property PACKAGE_PIN G15 [get_ports {scala_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rot_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rot_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scala_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scala_sw[0]}]